# golangci-lint configuration for the capn project
# This configuration addresses known issues with golangci-lint v1.55.2
# and embedded struct method resolution.

linters:
  enable:
    - gofmt          # Format checking
    - goimports      # Import organization and formatting
    - govet          # Go vet analysis
    - ineffassign    # Detect ineffectual assignments
    - misspell       # Spell checking
    - unused         # Detect unused code
    - gosimple       # Simplify code suggestions
    - staticcheck    # Advanced static analysis
    - errcheck       # Check error handling
    - gosec          # Security issues
    - goconst        # Detect repeated constants
    - gocyclo        # Cyclomatic complexity
    - typecheck      # Type checking (with exclusions below)

run:
  timeout: 5m
  skip-dirs:
    - vendor

issues:
  exclude-rules:
    # Known issue with golangci-lint v1.55.2: false positives with embedded struct methods
    # The Go compiler and 'go test' correctly resolve these methods, but golangci-lint doesn't
    - text: "undefined.*\\(type \\*FileAgent has no field or method"
      linters:
        - typecheck
    - text: "undefined.*\\(type \\*NetworkAgent has no field or method"
      linters:
        - typecheck  
    - text: "undefined.*\\(type \\*ResearchAgent has no field or method"
      linters:
        - typecheck
    - text: "undefined.*\\(type \\*MockLLMProvider has no field or method"
      linters:
        - typecheck

  # Maximum number of issues to report (0 = unlimited)
  max-issues-per-linter: 0
  max-same-issues: 0

# Configuration for specific linters
linters-settings:
  gocyclo:
    # Maximum cyclomatic complexity
    min-complexity: 15
  
  gosec:
    # Exclude specific security checks that may be too strict for this project
    excludes:
      - G204  # Subprocess launched with variable (may be acceptable in CLI tools)
  
  goconst:
    # Minimum length of string constant
    min-len: 3
    # Minimum occurrences count to trigger
    min-occurrences: 2
