global:
  verbose: false
  dry_run: false
  parallel: 5
  timeout: 5m

captain:
  max_concurrent_agents: 5
  planning_timeout: 30s
  # Set your OpenAI API key here or use OPENAI_API_KEY environment variable
  openai_api_key: "" 
  model: "gpt-4"
  max_tokens: 2000
  temperature: 0.7
  retry_attempts: 3
  retry_delay: 1s

crew:
  timeouts: {}

mcp:
  timeout: 10s
  retry_count: 3